import Head from "next/head";
import Image from "next/image";
import dbConnect from "../lib/dbConnect";
import Waifu from "../model/Waifu";
import styles from "../styles/Home.module.css";

export default function Home({ charas }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {charas?.map((chara) => (
            <a key={chara._id} href="#" className={styles.card}>
              <Image src={chara.image} width={500} height={500} objectFit="cover"/>
              <h3>{chara.name} &rarr;</h3>
              <p>{chara.description}</p>
            </a>
          ))}
        
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  await dbConnect();

  // find all the data in our database
  const result = await Waifu.find({});
  const charas = result.map((doc) => {
    const chara = doc.toObject();
    chara._id = chara._id.toString();


    return chara;
  });

  return { props: { charas: charas } };
}
