import Head from "next/head"
import Image from "next/image"
import dbConnect from "@src/lib/dbConnect"
import Waifu from "@src/model/Waifu"
import Link from "next/link"

export default function Home({ charas }) {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <Link href='/new'>New</Link>

        <p>
          Get started by editing <code>pages/index.js</code>
        </p>

        <div>
          {charas?.map(chara => (
            <div key={chara._id}>
              <div className='card'>
                <img
                  src={chara.image}
                  width={500}
                  height={500}
                  style={{ objectFit: "cover" }}
                />
                <h3>{chara.name} &rarr;</h3>
                <p>{chara.description}</p>
                <div>
                  <Link href={`/[id]/edit`} as={`/${chara._id}/edit`}>
                    <a className='btn edit'>Edit</a>
                  </Link>
                  <Link href='/[id]' as={`/${chara._id}`}>
                    <a className='btn view'>View</a>
                  </Link>
                </div>
              </div>
            </div>
          ))}
        </div>
      </main>

      <footer>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{" "}
          <span>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  await dbConnect()

  // find all the data in our database
  const result = await Waifu.find({})
  const charas = result.map(doc => {
    const chara = doc.toObject()
    chara._id = chara._id.toString()

    return chara
  })

  return { props: { charas: charas } }
}
